format_version: 2
environments:
  ci:
    pipelines:
      - "team1UI"
      
pipelines:
  "team1UI":
    group: team1
    materials:
      ui:
        git: "git@github.com:DevBootCampTW/bootcamp-just-cinemas-ui.git"
    stages:
      - test:
          jobs:
            test:
              resources:
                - node-and-java
              tasks:
                - script: |
                    yarn --ignore-engines install
                    yarn run test_with_coverage
      - build:
          jobs:
            build:
              resources:
                - node-and-java
              tasks:
                - script: |
                    yarn --ignore-engines install
                    REACT_APP_API_URL="http://18.211.150.89:9090" yarn run build              

      - deploy:
           jobs:
            deploy:
              resources:
                - node-and-java
              tasks:
                - script: |
                    sh ./buildAndDeploy/deploy.sh team1-bootcamp-march2018
